name: Release
on:
  release:
    types: [published]
jobs:
  release:
    uses: Solvely-Colin/solvely-launchpad/.github/workflows/release.yml@v1
    with:
      package-name: your-package-name
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
